# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: a30a9404496a4fe82593e043dafd80255cb74ef02f9ae9eb1809ac9b8a9f423a2a382cf9f6b23f2d6078bec1b329d661d8fcc0813956a45b09e991be714f88be

test:
  secret_key_base: a66fae0c0bbf85dfc2ee2e04e55794d74b74fcccee2c2d51a73a46be9babf9dc7c613f6132d32850624122a02563d8f788da3e9d37d9165b3f891bf39df21356

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
